
[tool.poetry]
name = "circuit_puzzles"
packages = [{include = "circuit_puzzles"}]
version = "0.1.0"
description = "Puzzles used in stablecoin protocol Circuit on Chia blockchain"
authors = ["Sebastjan Trepca <set@circuitdao.com>", "Nic Niedermowwe <nin@circuitdao.com>"]

[tool.poetry.dependencies]
python = "^3.8"
chialisp_loader = "^0.1.0"
clvm_rs = "^0.6.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
